apiVersion: v2
type: application
description: An extended Helm chart derived from official Prometheus Operator chart.
name: prometheus-operator
version: 0.2.2
appVersion: 0.38.1
home: https://coreos.com/operators/prometheus/docs/latest/
sources:
  - https://github.com/coreos/prometheus-operator
maintainers:
- name: sylus
  email: william.hearn@canada.ca
engine: gotpl
dependencies:
- name: prometheus-operator
  version: 9.3.1
  repository: https://kubernetes-charts.storage.googleapis.com/
