# Default values for sidecar-terminator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# Annotations to add to the Pod
podAnnotations: {}
# Labels to add to the Pod
podLabels: {}

image:
  repository: statcan/kubernetes-sidecar-terminator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

sidecarTerminator:
  # A list of namespace names to watch.
  # An empty list will watch all namespaces.
  namespaces: []
    # - kube-system
    # - sidecar-terminator

  # A list of sidecars to terminate.
  sidecars: {}
    #  # The name of the sidecar container.
    #- name: istio-proxy
    #  # The signal number to use when ending the process.
    #  # Defaults to 15 when not set.
    #  signalNumber:
    #- name: example
    #  signalNumber: 9

  # The image to use for terminating sidecars.
  # Notes:
  #   Requires the kill command.
  #   Requires the image to be available without authentication
  #     unless pods with sidecars already have access to the registry.
  terminatorImage: ""

imagePullSecrets: {}

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    cpu: 10m
    memory: 200M
  limits:
    cpu: 100m
    memory: 500M

nodeSelector: {}

tolerations: []

affinity: {}
