ci_slug: "fdi-meta"
namespace: "fdi"
configMap:
  name: "daaas-fdi-fluentd-config" #fdi namespace use daaas-fdi-fluentd-config aaw use org-fdi-system-fluentd-config
  cluster: ""
elastic:
  version: "8.3.3"
  host: "fdi-meta-elasticsearch.test.cloud.statcan.ca"
  store: "32Gi"
kibana:
  host: "fdi-meta-kibana.test.cloud.statcan.ca"
destinationrule:
  enable: false
