# Default values for mutating-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The domain of the cluster.
# Defaults to cluster.local
clusterDomain: cluster.local

replicaCount: 1
image:
  repository: mutating-webhook
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# Arguments to pass to the container.
arguments: []

# Configurations around certificates.
certificates:
  # The mount path of the certificates. 
  # Defaults to /certs.
  certsMountPath: /certs
  # Defines the duration of the certificates validity.
  duration: 720h0m0s # 30 days
  # Defines the amount of time before expiry when the certificate should be renewed.
  renewBefore: 120h0m0s # 5 days

# Configurations pertaining to configuring the Webhook
webhook:
  # The name of the admission webhook.
  # Name should be fully qualified, e.g., imagepolicy.kubernetes.io, where
  # "imagepolicy" is the name of the webhook, and kubernetes.io is the name
  # of the organization.
  name: 
  namespaceSelector:
    # matchExpressions:
    # - key: environment
    #   operator: In
    #   values: ["prod","staging"]
  # Defines how unrecognized errors and timeout errors from the admission webhook are handled.
  # Allowed values are Ignore or Fail.
  failurePolicy: Fail
  # Defines if the webhook should work on the exact resource or equivalents that are passed to the server.
  # (in regards to version)
  matchPolicy: Equivalent
  # Defines if mutating admission plugins observe changes made by other plugins.
  # Allowed values are Never or IfNeeded.
  reinvocationPolicy: Never
  # Defines if a webhook has a side-effect. Webhooks typically operate only on the content of the AdmissionReview sent to them.
  # Allowed values are Unknown, None, Some, NoneOnDryRun.
  sideEffects: Unknown
  # Rules describes what operations on what resources/subresources the webhook cares about. 
  # Note: resources should be lowercase and their plural name. 
  rules: 
    # - apiGroups:
    #   - ""
    #   apiVersions:
    #   - v1
    #   operations:
    #   - CREATE
    #   resources:
    #   - pods
    #   scope: '*'

imagePullSecrets: []
 # - name: "secretname"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


nodeSelector: {}

tolerations: []

affinity: {}
