apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: 
  namespace: fdi
spec:
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  version: {{ .Values.elastic.version }}
  nodeSets:
  - config:
      node.roles: 
        - master
        - data
        - ingest
      node.store.allow_mmap: false
    count: 1
    name: node
    podTemplate:
      metadata:
        annotations:
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
      spec:
        automountServiceAccountToken: true
        containers:
        - env:
          - name: ES_JAVA_OPTS
            value: -Xms4g -Xmx4g
          name: elasticsearch
          resources:
            limits:
              cpu: "4"
              memory: 8Gi
            requests:
              cpu: "2"
              memory: 8Gi
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        storageClassName: default
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 128Gi